# data_ispo/prinsip_2.py
# Data Master ISPO - Prinsip 2 (Sesuai Lampiran Permentan No. 33 Tahun 2025)

PRINSIP_2_DATA = {
    "prinsip_no": 2,
    "prinsip_nama": "PRAKTIK PERKEBUNAN YANG BAIK",
    "kriteria": [
        {
            "code": "2.1",
            "nama": "Perencanaan Perkebunan",
            "indikator": [
                {
                    "no": 1,
                    "deskripsi": "Perusahaan Perkebunan memiliki rencana strategis yang berisi visi dan misi yang mendukung usaha perkebunan kelapa sawit berkelanjutan. (I, B, P)",
                    "params": [
                        {
                            "text": "Tersedia dokumen visi dan misi Perusahaan Perkebunan yang mendukung usaha berkelanjutan yang disahkan oleh pimpinan Perusahaan Perkebunan.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki Rencana strategis.",
                            "fail": "Tidak memenuhi Jika tidak memiliki Rencana strategis.",
                        },
                        {
                            "text": "Tersedia bukti sosialisasi Visi dan Misi Perusahaan Perkebunan yang Mendukung usaha Berkelanjutan kepada pekerja dan mitra kerja.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika tersedia bukti sosialisasi.",
                            "fail": "Tidak memenuhi Jika tidak tersedia bukti sosialisasi.",
                        },
                    ],
                },
                {
                    "no": 2,
                    "deskripsi": "Perusahaan Perkebunan memiliki Struktur Organisasi Perusahaan Perkebunan Kelapa Sawit. (I, B, P)",
                    "params": [
                        {
                            "text": "Tersedia dokumen Struktur Organisasi Perusahaan Perkebunan Kelapa Sawit yang disahkan oleh Pimpinan.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki Struktur organisasi beserta uraian tugas yang lengkap.",
                            "fail": "Tidak memenuhi Jika tidak memiliki Struktur organisasi beserta uraian tugas yang lengkap.",
                        },
                        {
                            "text": "Tersedia Struktur Organisasi sesuai dengan kegiatan operasional, termasuk unit yang secara khusus menangani Sistem Rantai Pasok (SRP).",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki struktur organisasi sesuai kegiatan operasional dan unit SRP.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                        {
                            "text": "Tersedia uraian tugas dan tanggung jawab untuk setiap posisi dan level struktur organisasi.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki uraian tugas dan tanggung jawab lengkap.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                    ],
                },
                {
                    "no": 3,
                    "deskripsi": "Perusahaan Perkebunan memiliki perencanaan dan evaluasi seluruh kegiatan operasional usaha perkebunan kelapa sawit. (I, B, P)",
                    "params": [
                        {
                            "text": "Tersedia dokumen perencanaan jangka pendek, jangka menengah dan jangka panjang secara lengkap yang menjelaskan seluruh kegiatan operasional usaha perkebunan kelapa sawit.",
                            "doc": True,
                            "interview": False,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki perencanaan, monitoring dan evaluasi usaha perkebunan.",
                            "fail": "Tidak memenuhi Jika tidak memiliki perencanaan, monitoring dan evaluasi usaha perkebunan.",
                        },
                        {
                            "text": "Tersedia laporan pelaksanaan kegiatan/evaluasi tentang penerapan seluruh kegiatan operasional usaha perkebunan kelapa sawit.",
                            "doc": True,
                            "interview": False,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki laporan pelaksanaan kegiatan/evaluasi.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                        {
                            "text": "Tersedia laporan Hasil Audit Keuangan Perusahaan Perkebunan.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki laporan hasil audit keuangan.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                    ],
                },
                {
                    "no": 4,
                    "deskripsi": "Perusahaan Perkebunan memiliki Sistem Manajemen Sumber Daya Manusia (SDM). (I, B, P)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja terkait mekanisme pengorganisasian tenaga kerja dalam penerapan praktik budi daya. Termasuk pembagian tugas dan sistem rotasi kerja.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki sistem Manajemen SDM.",
                            "fail": "Tidak memenuhi Jika tidak memiliki Sistem manajemen SDM.",
                        },
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja terkait pelatihan tentang praktik budi daya perkebunan yang baik.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis pelatihan praktik budi daya.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                    ],
                },
                {
                    "no": 5,
                    "deskripsi": "Perusahaan Perkebunan memiliki dokumen rencana dan realisasi pemanfaatan lahan (HGU/HGB) untuk pembangunan perkebunan, unit pengolahan kelapa sawit, kantor, perumahan karyawan, sarana pendukung dan kebutuhan lainnya. (I, B, P)",
                    "params": [
                        {
                            "text": "Tersedia rencana dan realisasi luas pemanfaatan lahan sesuai dengan luas HGU dan/ atau HGB.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki dokumen rencana dan realisasi pemanfaatan lahan.",
                            "fail": "Tidak memenuhi Jika tidak memiliki dokumen rencana dan realisasi pemanfaatan lahan.",
                        },
                        {
                            "text": "Tersedia rencana dan realisasi kapasitas pabrik sesuai dengan izin usaha perkebunan/perizinan berusaha.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki rencana dan realisasi kapasitas pabrik.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                        {
                            "text": "Tersedia laporan Perkembangan usaha perkebunan tahunan yang dilaporkan kepada pemberi izin usaha perkebunan.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki laporan perkembangan usaha perkebunan tahunan.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                        {
                            "text": "Tersedia dokumen untuk mengusahakan seluruh areal yang secara teknis dapat ditanami sesuai dengan peraturan perundangan yang berlaku.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika tersedia dokumen pengusahaan seluruh areal.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                    ],
                },
            ],
        },
        {
            "code": "2.2",
            "nama": "Pembukaan dan Pengolahan Lahan",
            "indikator": [
                {
                    "no": 1,
                    "deskripsi": "Perusahaan Perkebunan wajib menerapkan kaidah pembukaan lahan baru dan operasional perkebunan tanpa bakar. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja terkait pembukaan lahan tanpa bakar sesuai ketentuan perundangan yang berlaku.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/IK, dokumen/rekaman, BA, Laporan dan/atau RKPPL untuk kegiatan pembukaan lahan baru dan operasional perkebunan tanpa bakar.",
                            "fail": "Tidak memenuhi Jika tidak memiliki SOP/Petunjuk teknis/IK, dokumen/rekaman, BA, Laporan dan/atau RKPPL untuk kegiatan pembukaan lahan baru dan operasional perkebunan tanpa bakar.",
                        },
                        {
                            "text": "Tersedia dokumen/rekaman implementasi kegiatan pembukaan lahan tanpa bakar.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia dokumen/rekaman implementasi pembukaan lahan tanpa bakar.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                        {
                            "text": "Tersedia identifikasi riwayat pemunculan titik api di area konsesi.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia identifikasi riwayat pemunculan titik api.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                        {
                            "text": "Tersedia Berita Acara (BA) pembukaan lahan secara manual/mekanis.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika tersedia Berita Acara pembukaan lahan manual/mekanis.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                        {
                            "text": "Tersedia laporan tindakan penanggulangan kebakaran.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika tersedia laporan tindakan penanggulangan kebakaran.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                        {
                            "text": "Jika terdapat rencana pembukaan lahan baru/peremajaan, tersedia dokumen RKPPLP yang disetujui oleh Kepala Dinas provinsi atau kabupaten/kota sesuai dengan kewenangan.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika tersedia dokumen RKPPLP disetujui instansi berwenang.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                    ],
                },
                {
                    "no": 2,
                    "deskripsi": "Perusahaan Perkebunan wajib menerapkan kaidah konservasi tanah dan air dalam proses pembukaan lahan baru, penataan lahan dan operasional perkebunan. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja terkait kegiatan pembukaan lahan baru, penataan lahan dan operasional perkebunan yang menerapkan kaidah konservasi tanah dan air, meliputi: a) jarak lindung sempadan; b) sistem drainase kemiringan <8%; c) pengawetan tanah fisik (tapak kuda/teras kontur); d) pengawetan tanah biologi (cover crops).",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja, dokumen/rekaman, BA, Laporan dalam menerapkan kaidah konservasi tanah dan air.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki SOP/Petunjuk teknis/Instruksi Kerja, dokumen/rekaman, BA, Laporan dalam menerapkan kaidah konservasi tanah dan air.",
                        },
                        {
                            "text": "Tersedia dokumen/rekaman implementasi pembukaan lahan baru, penataan lahan dan operasional perkebunan yang menerapkan kaidah konservasi tanah dan air sesuai dengan SOP/Petunjuk teknis/Instruksi Kerja yang telah ditetapkan.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia dokumen implementasi konservasi tanah dan air.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                        {
                            "text": "Tersedia rekaman dan peta penataan lahan meliputi penataan blok, pembuatan jalan kebun dan emplasement.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia rekaman dan peta penataan lahan.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                        {
                            "text": "Tersedia dokumen/rekaman konservasi tanah dan air secara fisik, kimia maupun biologi.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia dokumen rekaman konservasi fisik, kimia, maupun biologi.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                        {
                            "text": "Tersedia rekaman pembukaan lahan sesuai persyaratan dan kewajiban yang tercantum dalam izin lingkungan atau AMDAL/RKL-RPL yang sesuai ketentuan peraturan perundangan.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia rekaman sesuai izin lingkungan/AMDAL.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                    ],
                },
            ],
        },
        {
            "code": "2.3",
            "nama": "Perbenihan",
            "indikator": [
                {
                    "no": 1,
                    "deskripsi": "Perusahaan Perkebunan memiliki mekanisme terkait Perbenihan. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja penggunaan benih unggul.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja penggunaan benih unggul dan penangan benih tidak memenuhi persyaratan, serta rekaman implementasinya.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki SOP/Petunjuk teknis/Instruksi Kerja penggunaan benih unggul.",
                        },
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja penanganan benih yang tidak memenuhi persyaratan.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP penanganan benih tidak memenuhi syarat.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki.",
                        },
                        {
                            "text": "Tersedia dokumen/rekaman implementasi penggunaan benih unggul.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika tersedia rekaman implementasi penggunaan benih unggul.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                        {
                            "text": "Tersedia dokumen/rekaman/berita acara implementasi penanganan benih yang tidak memenuhi persyaratan.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika tersedia rekaman penanganan benih tidak memenuhi syarat.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                    ],
                },
                {
                    "no": 2,
                    "deskripsi": "Perusahaan Perkebunan memiliki dokumen pelaksanaan penyediaan benih bersertifikat. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia sertifikat benih dari produsen benih bersertifikat yang diterbitkan oleh instansi yang berwenang.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki Dokumen sertifikat benih dari produsen.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki Dokumen sertifikat benih dari produsen.",
                        },
                        {
                            "text": "Tersedia dokumen pelaksanaan pembelian kecambah mulai dari permohonan pembelian sampai kecambah diterima.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki dokumen pelaksanaan pembelian kecambah lengkap.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                    ],
                },
            ],
        },
        {
            "code": "2.4",
            "nama": "Penanaman pada Lahan Mineral dan/atau Penanaman pada Lahan Gambut",
            "indikator": [
                {
                    "no": 1,
                    "deskripsi": "Perusahaan Perkebunan memiliki mekanisme penanaman kelapa sawit di lahan mineral. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja terkait penanaman kelapa sawit pada lahan mineral sesuai dengan peraturan perundangan terkait pedoman budi daya kelapa sawit.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja sesuai peraturan perundangan yang berlaku dan dokumen rekaman implementasinya.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki SOP/Petunjuk teknis/Instruksi Kerja sesuai peraturan perundangan yang berlaku.",
                        },
                        {
                            "text": "Tersedia dokumen/rekaman implementasi penanaman kelapa sawit pada lahan mineral.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki dokumen implementasi penanaman di lahan mineral.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                    ],
                },
                {
                    "no": 2,
                    "deskripsi": "Perusahaan Perkebunan memiliki mekanisme penanaman kelapa sawit di lahan gambut. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja penanaman dan pengelolaan lahan gambut sesuai peraturan perundangan.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja sesuai peraturan perundangan yang berlaku, alat ukur, dokumen hasil identifikasi, dan dokumen rekaman implementasinya.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki SOP/Petunjuk teknis/Instruksi Kerja lahan gambut.",
                        },
                        {
                            "text": "Tersedia dokumen rekaman implementasi SOP/Petunjuk teknis/Instruksi Kerja pengelolaan lahan gambut.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki dokumen rekaman implementasi pengelolaan gambut.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                        {
                            "text": "Tersedia dokumen hasil identifikasi dan pemetaan pada ekosistem gambut dengan fungsi lindung.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki dokumen hasil identifikasi ekosistem gambut fungsi lindung.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                        {
                            "text": "Tersedia dokumen hasil identifikasi kedalaman gambut di areal HGU yang dilakukan oleh pihak internal atau eksternal perusahaan.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki dokumen identifikasi kedalaman gambut.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                        {
                            "text": "Tersedia alat untuk mengukur penurunan lapisan tanah gambut.",
                            "doc": True,
                            "interview": False,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia alat pengukur subsidensi gambut.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                        {
                            "text": "Tersedia sarana dan prasarana terkait pengelolaan penanaman di lahan gambut.",
                            "doc": True,
                            "interview": False,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia sarana prasarana pengelolaan gambut.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                        {
                            "text": "Tersedia hasil monitoring subsidensi dan pengaturan tinggi muka air tanah.",
                            "doc": True,
                            "interview": False,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia hasil monitoring subsidensi dan tinggi muka air tanah.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                    ],
                },
            ],
        },
        {
            "code": "2.5",
            "nama": "Pemeliharaan Tanaman",
            "indikator": [
                {
                    "no": 1,
                    "deskripsi": "Perusahaan Perkebunan memiliki mekanisme terkait pemeliharaan tanaman kelapa sawit. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja pemeliharaan tanaman sesuai dengan peraturan perundangan terkait pedoman budi daya kelapa sawit.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja pemeliharaan tanaman.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki SOP/Petunjuk teknis/Instruksi Kerja pemeliharaan tanaman.",
                        },
                        {
                            "text": "Tersedia dokumen rencana pemeliharaan tanaman (konsolidasi, penyisipan, piringan, penutup tanah, pemupukan daun/tanah, terasering, drainase, tunas pasir).",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki rencana pemeliharaan tanaman.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki rencana pemeliharaan tanaman.",
                        },
                        {
                            "text": "Tersedia dokumen rekaman implementasi pemeliharaan tanaman tahun berjalan dan 1 (satu) tahun sebelumnya.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki dokumen rekaman implementasi pemeliharaan tanaman tahun berjalan dan 1 (satu) tahun sebelumnya.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki.",
                        },
                    ],
                },
            ],
        },
        {
            "code": "2.6",
            "nama": "Pengendalian Organisme Pengganggu Tumbuhan (OPT)",
            "indikator": [
                {
                    "no": 1,
                    "deskripsi": "Perusahaan Perkebunan memiliki mekanisme pengamatan dan pengendalian OPT, serta menerapkan Sistem Pengendalian Hama Terpadu (PHT) sesuai Pedoman Teknis. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja pengamatan dan pengendalian OPT secara terpadu (PHT), EWS, daftar pestisida terdaftar, penanganan limbah pestisida, regu terlatih, gudang pestisida, dan musuh alami.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja pengamatan dan pengendalian OPT, dan dokumen rekaman implementasinya.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki SOP/Petunjuk teknis/Instruksi Kerja pengamatan dan pengendalian OPT.",
                        },
                        {
                            "text": "Tersedia dokumen rekaman implementasi pengamatan dan pengendalian OPT sesuai prinsip PHT dan ketentuan Komisi Pestisida.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki dokumen rekaman implementasi PHT.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                    ],
                },
                {
                    "no": 2,
                    "deskripsi": "Perusahaan Perkebunan memiliki mekanisme terkait mitigasi penggunaan pestisida. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja penanganan dan pengelolaan pestisida (penggolongan, tata cara penggunaan, penyimpanan, keracunan & gejalanya, serta P3K).",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja penanganan dan pengelolaan pestisida, dan dokumen rekaman implementasinya.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki SOP/Petunjuk pengelolaan pestisida.",
                        },
                        {
                            "text": "Tersedia dokumen rekaman implementasi penanganan dan pengelolaan pestisida di lapangan.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia rekaman implementasi pengelolaan pestisida.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                    ],
                },
                {
                    "no": 3,
                    "deskripsi": "Perusahaan Perkebunan memiliki komitmen tertulis dari pihak manajemen Perusahaan Perkebunan untuk pengurangan pestisida dalam kegiatan operasional perkebunan. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia dokumen tertulis terkait komitmen dalam pengurangan bahan pestisida pada kegiatan pemeliharaan tanaman.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki dokumen komitmen tertulis, dokumen rekaman penggunaan pestisida, upaya pengurangannya serta inventarisasi penggunaan agensia hayati.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki dokumen komitmen tertulis.",
                        },
                        {
                            "text": "Tersedia rekaman penggunaan pestisida dan pengurangannya sampai batas tertentu dengan subtitusi bahan ramah lingkungan/agensia hayati.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia rekaman pengurangan pestisida dan pemanfaatan agensia hayati.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                    ],
                },
            ],
        },
        {
            "code": "2.7",
            "nama": "Pemanenan",
            "indikator": [
                {
                    "no": 1,
                    "deskripsi": "Perusahaan Perkebunan memiliki mekanisme terkait pemanenan Kelapa Sawit. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja pelaksanaan pemanenan dan kriteria TBS matang panen sesuai dengan peraturan perundangan terkait pedoman budi daya kelapa sawit.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja pelaksanaan pemanenan, serta dokumen rekaman implementasinya.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki SOP/Petunjuk pelaksanaan panen.",
                        },
                        {
                            "text": "Tersedia dokumen rekaman implementasi pemanenan TBS sesuai dengan pedoman budi daya.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia rekaman implementasi pemanenan TBS.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                    ],
                },
                {
                    "no": 2,
                    "deskripsi": "Perusahaan Perkebunan memiliki data produksi dan produktivitas, serta data proyeksi 1 (satu) tahun ke depan. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia data produksi dan produktivitas kebun secara periodik (bulanan, triwulan, semester dan tahunan).",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki data produksi dan produktivitas kebun secara periodik dan data proyeksi produksi 1 (satu) tahun ke depan.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki data produksi.",
                        },
                        {
                            "text": "Tersedia data proyeksi produksi dan produktivitas kebun 1 (satu) tahun ke depan.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki data proyeksi produksi 1 tahun ke depan.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                    ],
                },
            ],
        },
        {
            "code": "2.8",
            "nama": "Pengangkutan TBS",
            "indikator": [
                {
                    "no": 1,
                    "deskripsi": "Perusahaan Perkebunan memiliki mekanisme terkait pengangkutan TBS secara efektif dan efisien untuk menghindari restan dan penurunan mutu TBS. (I, B)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja pelaksanaan pengangkutan TBS (manajemen waktu/rute, jenis/kapasitas kendaraan, muatan, keamanan, monitoring waktu kebun ke PKS).",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja pengangkutan TBS, serta dokumen rekaman implementasinya.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki SOP pengangkutan TBS.",
                        },
                        {
                            "text": "Tersedia dokumen rekaman implementasi pelaksanaan pengangkutan TBS sesuai SOP.",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika tersedia dokumen rekaman implementasi pengangkutan TBS.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                    ],
                },
            ],
        },
        {
            "code": "2.9",
            "nama": "Penerimaan TBS di Unit Pengolahan Kelapa Sawit",
            "indikator": [
                {
                    "no": 1,
                    "deskripsi": "Perusahaan Perkebunan memiliki mekanisme penerimaan TBS sesuai peraturan perundangan yang berlaku. (I, P)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja penerimaan TBS di pabrik pengolahan kelapa sawit (registrasi dokumen, timbang bruto/tara, kriteria TBS, sortasi mutu, pencatatan & pembayaran).",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja penerimaan TBS di pabrik pengolahan kelapa sawit, serta dokumen rekaman implementasi pelaksanaan.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki SOP penerimaan TBS.",
                        },
                        {
                            "text": "Tersedia dokumen rekaman penerimaan TBS di pabrik pengolahan kelapa sawit (nama pemasok, alamat/lokasi kebun, status ISPO, tanggal, mutu, harga/pembayaran).",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki rekaman penerimaan TBS lengkap.",
                            "fail": "Tidak memenuhi Jika tidak memiliki.",
                        },
                    ],
                },
                {
                    "no": 2,
                    "deskripsi": "Perusahaan Perkebunan memiliki sarana dan prasarana pengiriman TBS dari lokasi kebun (TPH) menuju tempat pengolahan (PKS). (I, P)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi terkait pemeliharaan sarana prasarana penerimaan TBS (jalan kebun/TPH ke PKS, jembatan timbang, area sortasi, ramp bongkar muat).",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja pemeliharaan sarana prasarana penerimaan TBS, serta dokumen rekaman implementasi pelaksanaan.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki.",
                        },
                        {
                            "text": "Tersedia dokumen rekaman implementasi pemeliharaan sarana prasarana penerimaan TBS.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia rekaman implementasi pemeliharaan sarana prasarana.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                    ],
                },
            ],
        },
        {
            "code": "2.10",
            "nama": "Pengolahan TBS",
            "indikator": [
                {
                    "no": 1,
                    "deskripsi": "Perusahaan Perkebunan memiliki mekanisme terkait proses pengolahan, proses pemantauan dan pengukuran kualitas produk olahan TBS. (I, P)",
                    "params": [
                        {
                            "text": "Tersedia SOP/Petunjuk teknis/Instruksi Kerja proses pengolahan TBS sesuai GMP (perencanaan produksi, pengukuran kualitas produk olahan TBS).",
                            "doc": True,
                            "interview": True,
                            "obs": False,
                            "pass": "Memenuhi Jika memiliki SOP/Petunjuk teknis/Instruksi Kerja proses pengolahan TBS, serta dokumen rekaman implementasinya.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki SOP proses pengolahan TBS.",
                        },
                        {
                            "text": "Tersedia dokumen rekaman implementasi proses pengolahan TBS sesuai GMP.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika tersedia dokumen rekaman implementasi pengolahan TBS.",
                            "fail": "Tidak memenuhi Jika tidak tersedia.",
                        },
                    ],
                },
                {
                    "no": 2,
                    "deskripsi": "Perusahaan Perkebunan memiliki dokumen penggunaan air untuk unit pengolahan kelapa sawit. (I, P)",
                    "params": [
                        {
                            "text": "Tersedia dokumen penggunaan air untuk unit pengolahan kelapa sawit.",
                            "doc": True,
                            "interview": True,
                            "obs": True,
                            "pass": "Memenuhi Jika memiliki dokumen penggunaan air.",
                            "fail": "Tidak Memenuhi Jika tidak memiliki dokumen penggunaan air.",
                        },
                    ],
                },
            ],
        },
    ],
}